---
title: "Homework_fifth"
author: "Anna Grzegorzewicz"
date: "2023-11-29"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reading in and cleaning the data.



```{r cars}
library(tidyverse)
library(magrittr)
library(ggthemes)
library(scales)
library(lubridate)
homocides <- read_csv(file = "data-raw/homicide-data.csv")%>% 
  unite(col = city_state, c(city, state), sep = ", ") %>% 
  filter(city_state == "Baltimore, MD") %>%
  mutate(reported_date = ymd(reported_date)) %>% 
   mutate(year = year(reported_date), month = month(reported_date)) %>% 
  group_by(year, month) %>% count() %>%  
  mutate(date = make_date(year, month)) %>% 
   mutate(season = ifelse(month >= 5, "summer", ifelse (month <=10, "winter")))


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
